// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2pimAq4ZE6RpxYqoJGq0NK4u8jacpqqU',
    appId: '1:681647370392:web:e7ac98cd0e3127a32560ed',
    messagingSenderId: '681647370392',
    projectId: 'liveasy-9db4e',
    authDomain: 'liveasy-9db4e.firebaseapp.com',
    storageBucket: 'liveasy-9db4e.firebasestorage.app',
    measurementId: 'G-TMY63WD7NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFvzQSq4kft4MYV82c3HOF1qjVSCwJKrc',
    appId: '1:681647370392:android:920046fe70f88abb2560ed',
    messagingSenderId: '681647370392',
    projectId: 'liveasy-9db4e',
    storageBucket: 'liveasy-9db4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ4likWwoOXGvkT4RyOoUrrhZfVk8Nfkw',
    appId: '1:681647370392:ios:f77a1367de79d46c2560ed',
    messagingSenderId: '681647370392',
    projectId: 'liveasy-9db4e',
    storageBucket: 'liveasy-9db4e.firebasestorage.app',
    iosBundleId: 'com.example.liveasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ4likWwoOXGvkT4RyOoUrrhZfVk8Nfkw',
    appId: '1:681647370392:ios:f77a1367de79d46c2560ed',
    messagingSenderId: '681647370392',
    projectId: 'liveasy-9db4e',
    storageBucket: 'liveasy-9db4e.firebasestorage.app',
    iosBundleId: 'com.example.liveasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2pimAq4ZE6RpxYqoJGq0NK4u8jacpqqU',
    appId: '1:681647370392:web:3e2b55169c3967272560ed',
    messagingSenderId: '681647370392',
    projectId: 'liveasy-9db4e',
    authDomain: 'liveasy-9db4e.firebaseapp.com',
    storageBucket: 'liveasy-9db4e.firebasestorage.app',
    measurementId: 'G-R3YVR3PQB1',
  );

}